version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  postgres_db:
    image: postgres:14.1-alpine
    restart: always
    env_file: .pg_env
    expose:
      - "5432"
    volumes: 
      - postgres_db_volume:/var/lib/postgresql/data      

  etl_process:
    build: postgres_to_es
    env_file:
      - ./postgres_to_es/.env
    depends_on:
      - postgres_db
      - elasticsearch

volumes:
  postgres_db_volume:
  esdata: