version: '3'
services:
  postgres_db:
    ports:
      - "5432:5432"
    volumes: 
      - postgres_db_volume:/var/lib/postgresql/data      

volumes:
  postgres_db_volume:
    external: 
      name: movies_service_postgres_db