version: '3'
services:
  postgres_db:
    ports:
      - "5432:5432"
    volumes: 
      - postgres_db_volume:/var/lib/postgresql/data      

  elasticsearch:
    environment:
        - xpack.security.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  postgres_db_volume:
    external: 
      name: movies_service_postgres_db